apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./install.yaml
namespace: argocd

patches:
  - patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server
